version: 2
jobs:
  test_classification_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.10
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements/test_requirements.txt
            PYTHONPATH=. python3 taxi_tips_model/dataset_downloader.py
            py.test -vv tests
workflows:
  version: 2
  test-all:
    jobs:
      - test_classification_model