version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.9
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install wheel

fetch_data: &fetch_data
  run:
    name: Download data
    command: |
      source venv/bin/activate
      PYTHONPATH=. python3 taxi_tips_model/dataset_downloader.py

jobs:
  test_classification_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Install requirements
          command: |
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements/test_requirements.txt
      - *fetch_data
      - run:
          name: Train model
          command: |
            source venv/bin/activate
            mkdir taxi_tips_model/trained_models  
            PYTHONPATH=. python3 taxi_tips_model/train_pipeline.py
      - run:
          name: Runnning tests
          command: |
            py.test -vv tests

  train_and_upload_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run: 
          name: Install requirements
          command: |
            source venv/bin/activate
            pip install -r requirements/requirements.txt
      - *fetch_data
      - run: 
          name: Train model
          command: |
            source venv/bin/activate
            PYTHONPATH=. python3 taxi_tips_model/train_pipeline.py
      - run:
          name: Publish model to Gemfury
          command: |
            source venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh ./taxi_tips_model

workflows:
  version: 2
  test-all:
    jobs:
      - train_and_upload_model
      # - train_and_upload_model:
          # requires:
            # - test_classification_model